version: "2"
services:

#  jaeger-all-in-one:
#    image: jaegertracing/all-in-one:latest
#    restart: always
#    ports:
#      - "16686:16686"
#      - "14268:14268"
#      - "14250:14250"
  #  networks:
  #    - opentelemetry

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:0.79.0
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml", ""]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
 #   networks:
 #     - opentelemetry
 #   depends_on:
 #     - jaeger-all-in-one

# Red de Elastic
volumes:
  data01:
    driver: local

#networks:
#  opentelemetry:
#    driver: bridge